output "dbt_connection_details" {
  value = {
    hostname  = module.databricks.sql_warehouse_hostname
    http_path = module.databricks.sql_warehouse_http_path
  }
  description = "Copy-paste configurations for dbt Cloud / Local connections"
}
output "dbt_token_value" {
  value     = module.databricks.dbt_token_value
  sensitive = true
  description = "The automated pipeline token generated by Databricks for dbt core"
}