variable "resource_group_name" {}
variable "location"            {}
variable "environment"         {}
variable "dbt_sp_application_id" {
  type        = string
  description = "The Client/Application ID generated by AzureAD for the dbt Service Principal"
}