# azure-pipelines/ci-pipeline.yml
trigger: none

pr:
  branches:
    include:
      - main
      - staging
      - dev

pool:
  name: laptop-pool

steps:
  - script: | 
      python3 --version
      python3 -m pip install --upgrade pip
    displayName: 'Verify and Upgrade Pip'
    
  - script: | 
      python3 -m venv venv
      call venv\Scripts\activate
      python3 -m pip install --upgrade pip3
      pip3 install -r requirements.txt
    displayName: 'Install dependencies in Venv'

  - script: | 
      call venv\Scripts\activate
      flake8 src/ --max-line-length=120
    displayName: 'Lint'

  - script: |
      call venv\Scripts\activate
      pytest src/tests/ -v --cov=src --cov-report=xml
    displayName: 'Unit tests'

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      command: init
      workingDirectory: infrastructure/terraform/environments/dev
      backendServiceArm: 'azure-service-connection'
      backendAzureRmResourceGroupName: 'rg-terraform-state'
      backendAzureRmStorageAccountName: 'stdbricsanaltrfrm'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'dev.terraform.tfstate'

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      command: plan
      workingDirectory: infrastructure/terraform/environments/dev
      environmentServiceNameAzureRM: 'azure-service-connection'