trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

pool:
  name: laptop-pool

variables:
  - group: databricks-analytics-dev-secrets
  - name: PYTHON_EXE
    value: 'C:\Users\Torey\AppData\Local\Programs\Python\Python314\python.exe'

steps:
  
  - script: |
      # 1. Create the parent folder if it doesn't exist
      if not exist C:\azure_devops_venvs mkdir C:\azure_devops_venvs
      
      SET CENTRAL_VENV=C:\azure_devops_venvs\databricks_project_venv

      if not exist %CENTRAL_VENV% (
        echo "Central Venv missing. Creating..."
        "$(PYTHON_EXE)" -m venv %CENTRAL_VENV%
        %CENTRAL_VENV%\Scripts\python.exe -m pip install --upgrade pip
      )
      
      %CENTRAL_VENV%\Scripts\pip.exe install -r requirements.txt
      
      # This line makes 'flake8' and 'pytest' available globally for the rest of the job
      echo ##vso[task.prependpath]%CENTRAL_VENV%\Scripts
    displayName: 'Global Local Dependency Sync'

  - script: |
      flake8 src/ --max-line-length=120
    displayName: 'Lint'

  - script: |
      # NO MORE venv\Scripts\ prefix here!
      pytest src/tests/ -v --cov=src --cov-report=xml
      if %errorlevel% equ 5 exit 0
    displayName: 'Unit tests'

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      command: init
      workingDirectory: infrastructure/terraform/environments/dev
      backendServiceArm: 'azure-service-connection'
      backendAzureRmResourceGroupName: 'rg-terraform-state'
      backendAzureRmStorageAccountName: 'stdbricsanaltrfrm'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'dev.terraform.tfstate'

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      command: plan
      workingDirectory: infrastructure/terraform/environments/dev
      environmentServiceNameAzureRM: 'azure-service-connection'
    env:
      TF_VAR_tenant_id: $(AZURE_TENANT_ID)
      TF_VAR_subscription_id: $(AZURE_SUBSCRIPTION_ID)

  # 2. AUTOMATED APPLY (Only runs on merges to 'dev')
  - task: TerraformTaskV4@4
    displayName: Terraform Apply
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    inputs:
      command: apply
      workingDirectory: infrastructure/terraform/environments/dev
      environmentServiceNameAzureRM: 'azure-service-connection'
    env:
      TF_VAR_tenant_id: $(AZURE_TENANT_ID)
      TF_VAR_subscription_id: $(AZURE_SUBSCRIPTION_ID)